# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: Multiplication
      POSTGRES_PASSWORD: Nuttirtools
      POSTGRES_DB: GameForum
    ports:
      - "5432:5432"