swagger: '2.0'
info:
  description: This is a simple Web-application that is a game forum
  version: 1.0.0
  title: Swagger GameForum
  termsOfService: http://swagger.io/terms/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: localhost:8080
basePath: /
tags:
  - name: category-controller
    description: Category Controller
  - name: file-loader-controller
    description: File Loader Controller
  - name: forum-controller
    description: Forum Controller
  - name: publication-controller
    description: Publication Controller
  - name: user-controller
    description: User Controller
paths:
  /game-forum/category/create:
    post:
      tags:
        - category-controller
      summary: addCategory
      operationId: addCategoryUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: categoryDto
          description: categoryDto
          required: true
          schema:
            $ref: '#/definitions/CategoryDto'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /game-forum/category/delete/category:
    delete:
      tags:
        - category-controller
      summary: deleteCategoryByName
      operationId: deleteCategoryByNameUsingDELETE
      produces:
        - application/json
      parameters:
        - name: categoryName
          in: query
          description: categoryName
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /game-forum/category/update:
    put:
      tags:
        - category-controller
      summary: updateCategory
      operationId: updateCategoryUsingPUT
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: categoryDto
          description: categoryDto
          required: true
          schema:
            $ref: '#/definitions/CategoryDto'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /game-forum/file/{fileName}:
    get:
      tags:
        - file-loader-controller
      summary: download
      operationId: downloadUsingGET
      produces:
        - multipart/form-data
      parameters:
        - name: fileName
          in: path
          description: fileName
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    post:
      tags:
        - file-loader-controller
      summary: upload
      operationId: uploadUsingPOST
      consumes:
        - multipart/form-data
      produces:
        - '*/*'
      parameters:
        - name: file
          in: formData
          required: false
          type: file
        - name: fileName
          in: path
          description: fileName
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /game-forum/forum/all-category:
    get:
      tags:
        - forum-controller
      summary: getAllCategories
      operationId: getAllCategoriesUsingGET
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /game-forum/forum/all-publications:
    get:
      tags:
        - forum-controller
      summary: getAllPublications
      operationId: getAllPublicationsUsingGET
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /game-forum/forum/post/category:
    get:
      tags:
        - forum-controller
      summary: findPublicationsByCategory
      operationId: findPublicationsByCategoryUsingGET
      produces:
        - application/json
      parameters:
        - name: id
          in: query
          description: id
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /game-forum/forum/rating:
    get:
      tags:
        - forum-controller
      summary: getRatingPublications
      operationId: getRatingPublicationsUsingGET
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /game-forum/forum/title:
    get:
      tags:
        - forum-controller
      summary: findPublicationsByTitle
      operationId: findPublicationsByTitleUsingGET
      produces:
        - application/json
      parameters:
        - name: titleName
          in: query
          description: titleName
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /game-forum/forum/user/name:
    get:
      tags:
        - forum-controller
      summary: findUserByName
      operationId: findUserByNameUsingGET
      produces:
        - application/json
      parameters:
        - name: username
          in: query
          description: username
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /game-forum/forum/{publicationId}:
    get:
      tags:
        - forum-controller
      summary: findPublicationById
      operationId: findPublicationByIdUsingGET
      produces:
        - application/json
      parameters:
        - name: publicationId
          in: path
          description: publicationId
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /game-forum/publication/create:
    post:
      tags:
        - publication-controller
      summary: addPublication
      operationId: addPublicationUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: publicationDto
          description: publicationDto
          required: true
          schema:
            $ref: '#/definitions/PublicationDto'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /game-forum/publication/update:
    put:
      tags:
        - publication-controller
      summary: updatePublication
      operationId: updatePublicationUsingPUT
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: publicationDto
          description: publicationDto
          required: true
          schema:
            $ref: '#/definitions/PublicationDto'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /game-forum/publication/{publicationId}:
    delete:
      tags:
        - publication-controller
      summary: deletePublication
      operationId: deletePublicationUsingDELETE
      produces:
        - application/json
      parameters:
        - name: publicationId
          in: path
          description: publicationId
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /game-forum/user/create:
    post:
      tags:
        - user-controller
      summary: createUser
      operationId: createUserUsingPOST
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: userSecurityDto
          description: userSecurityDto
          required: true
          schema:
            $ref: '#/definitions/UserSecurityDto'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /game-forum/user/login:
    post:
      tags:
        - user-controller
      summary: loginUser
      operationId: loginUserUsingPOST
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: userSecurityDto
          description: userSecurityDto
          required: true
          schema:
            $ref: '#/definitions/UserSecurityDto'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /game-forum/user/logout:
    post:
      tags:
        - user-controller
      summary: logoutUser
      operationId: logoutUserUsingPOST
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: userDto
          description: userDto
          required: true
          schema:
            $ref: '#/definitions/UserDto'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /game-forum/user/update:
    put:
      tags:
        - user-controller
      summary: updateUser
      operationId: updateUserUsingPUT
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: userDto
          description: userDto
          required: true
          schema:
            $ref: '#/definitions/UserDto'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /game-forum/user/{username}:
    delete:
      tags:
        - user-controller
      summary: deleteUser
      operationId: deleteUserUsingDELETE
      produces:
        - application/json
      parameters:
        - name: username
          in: path
          description: username
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ResponseEntity'
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
definitions:
  CategoryDto:
    type: object
    properties:
      categoryId:
        type: integer
        format: int64
      categoryName:
        type: string
    title: CategoryDto
  PublicationDto:
    type: object
    properties:
      categoryId:
        type: integer
        format: int64
      categoryName:
        type: string
      content:
        type: string
      likes:
        type: integer
        format: int64
      photo:
        type: string
        format: byte
      publicationId:
        type: integer
        format: int64
      shipDate:
        type: string
        format: date-time
      status:
        type: string
        enum:
          - DELETED
          - EDITED
          - EXISTS
      title:
        type: string
      userId:
        type: integer
        format: int64
      username:
        type: string
    title: PublicationDto
  ResponseEntity:
    type: object
    properties:
      body:
        type: object
      statusCode:
        type: string
        enum:
          - ACCEPTED
          - ALREADY_REPORTED
          - BAD_GATEWAY
          - BAD_REQUEST
          - BANDWIDTH_LIMIT_EXCEEDED
          - CHECKPOINT
          - CONFLICT
          - CONTINUE
          - CREATED
          - DESTINATION_LOCKED
          - EXPECTATION_FAILED
          - FAILED_DEPENDENCY
          - FORBIDDEN
          - FOUND
          - GATEWAY_TIMEOUT
          - GONE
          - HTTP_VERSION_NOT_SUPPORTED
          - IM_USED
          - INSUFFICIENT_SPACE_ON_RESOURCE
          - INSUFFICIENT_STORAGE
          - INTERNAL_SERVER_ERROR
          - I_AM_A_TEAPOT
          - LENGTH_REQUIRED
          - LOCKED
          - LOOP_DETECTED
          - METHOD_FAILURE
          - METHOD_NOT_ALLOWED
          - MOVED_PERMANENTLY
          - MOVED_TEMPORARILY
          - MULTIPLE_CHOICES
          - MULTI_STATUS
          - NETWORK_AUTHENTICATION_REQUIRED
          - NON_AUTHORITATIVE_INFORMATION
          - NOT_ACCEPTABLE
          - NOT_EXTENDED
          - NOT_FOUND
          - NOT_IMPLEMENTED
          - NOT_MODIFIED
          - NO_CONTENT
          - OK
          - PARTIAL_CONTENT
          - PAYLOAD_TOO_LARGE
          - PAYMENT_REQUIRED
          - PERMANENT_REDIRECT
          - PRECONDITION_FAILED
          - PRECONDITION_REQUIRED
          - PROCESSING
          - PROXY_AUTHENTICATION_REQUIRED
          - REQUESTED_RANGE_NOT_SATISFIABLE
          - REQUEST_ENTITY_TOO_LARGE
          - REQUEST_HEADER_FIELDS_TOO_LARGE
          - REQUEST_TIMEOUT
          - REQUEST_URI_TOO_LONG
          - RESET_CONTENT
          - SEE_OTHER
          - SERVICE_UNAVAILABLE
          - SWITCHING_PROTOCOLS
          - TEMPORARY_REDIRECT
          - TOO_EARLY
          - TOO_MANY_REQUESTS
          - UNAUTHORIZED
          - UNAVAILABLE_FOR_LEGAL_REASONS
          - UNPROCESSABLE_ENTITY
          - UNSUPPORTED_MEDIA_TYPE
          - UPGRADE_REQUIRED
          - URI_TOO_LONG
          - USE_PROXY
          - VARIANT_ALSO_NEGOTIATES
      statusCodeValue:
        type: integer
        format: int32
    title: ResponseEntity
  UserDto:
    type: object
    properties:
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      password:
        type: string
      phone:
        type: string
      userId:
        type: integer
        format: int64
      userRole:
        type: string
        enum:
          - ADMIN
          - USER
          - VISITOR
      username:
        type: string
    title: UserDto
  UserSecurityDto:
    type: object
    properties:
      password:
        type: string
      username:
        type: string
    title: UserSecurityDto